on:
  push:
  workflow_dispatch:

jobs:
  publish:
    strategy:      
      matrix:
        number: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
        include:
          - name: "@jcansdale-test/npm-errors"
          - repository: "https://github.com/${{ github.repository }}"
          - _authToken: "${GITHUB_TOKEN}"
          - registry: https://npm.pkg.github.com
          - number: 0
          - number: 1
            name: "@jcansdale-test/NPM-ERRORS"
          - number: 2
            name: "@JCANSDALE-TEST/npm-errors"
          - number: 3
            name: "@jcansdale-missing/npm-errors"
          - number: 4
            repository: "https://github.com/jcansdale/nuget-errors"
          - number: 5
            _authToken: "invalid"
          - number: 6
            _authToken: "invalid"
          - number: 7
            _authToken: "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" # no-scope token
          - number: 8
            _authToken: $READ_AND_WRITE_PACKAGES_TOKEN
          - number: 9
            registry: https://npm.pkg.github.com/jcansdale-test
          - number: 10
            registry: https://npm.pkg.github.com/@jcansdale-test
          - number: 11
            registry: https://npm.pkg.github.com/jcansdale
          - number: 12
            registry: https://npm.pkg.github.com/---unknown---
          - number: 13
            registry: https://registry.npmjs.org
          - number: 14
            registry: https://github.org
          - number: 15
            name: "npm-errors"
            registry: https://npm.pkg.github.com/@jcansdale-test
          - number: 16
            registry: npm.pkg.github.com
          - number: 17
            repository: "${{ github.repository }}"
          - number: 18
            registry: https://npm.pkg.github.com/${{ github.repository }}
          - number: 19
            name: "jcansdale-test/npm-errors"
          - number: 20
            name: "jcansdale-test/npm-errors"
            registry: https://npm.pkg.github.com/jcansdale-test
          - number: 21
            name: "@jcansdale-test/util"
          - number: 22
            name: "@jcansdale-test/npm.errors"
      fail-fast: false

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    env:
      READ_AND_WRITE_PACKAGES_TOKEN: ${{ secrets.READ_AND_WRITE_PACKAGES_TOKEN }}

    steps:
    - name: create package.json
      run: |
        cat <<- EOF > package.json
        {
          "name": "${{ matrix.name }}",
          "version": "1.0.0-g${{ github.sha }}-${{ matrix.number }}",
          "repository": "${{ matrix.repository }}"
        }
        EOF
    - run: echo '//npm.pkg.github.com/:_authToken=${{ matrix._authToken }}' > .npmrc
    - run: npm publish --registry=${{ matrix.registry }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
